[package]
name = "rex4p"
version = "0.1.0"
edition = "2024"

[lib]
name = "rex4p"
crate-type = ["cdylib"]

[dependencies]
rex-core = { path = "../../crates/rex-core" }
rex-client = { path = "../../crates/rex-client" }
pyo3 = { version = "0.27", features = ["abi3-py39", "abi3"] }
