[package]
name = "rex4p"
version.workspace = true
edition.workspace = true

[lib]
name = "rex4p"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
rex-core = { path = "../../crates/rex-core" }
rex-client = { path = "../../crates/rex-client" }
pyo3 = { version = "0.27", features = ["extension-module", "abi3-py39"] }
pyo3-async-runtimes = { version = "0.27", features = ["tokio-runtime"] }
tokio.workspace = true
anyhow.workspace = true
bytes.workspace = true
async-trait.workspace = true
